sudo: false
language: python
matrix:
  include:
    - python: '3.8'
      env: TOXENV=py38-djmaster-dtmaster-tests
    - python: '3.8'
      env: TOXENV=py38-dj3.0-dt2.3-tests
    - python: '3.8'
      env: TOXENV=py38-dj3.0-dtmaster-tests
    - python: '3.8'
      env: TOXENV=py38-dj3.1-dt2.3-tests
    - python: '3.8'
      env: TOXENV=py38-dj3.1-dtmaster-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.0-dt1.19-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.0-dt1.21-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.0-dt2.0-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.0-dt2.1-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.0-dt2.2-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.1-dt1.19-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.1-dt1.21-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.1-dt2.0-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.1-dt2.1-tests
    - python: '3.6'
      env: TOXENV=py36-dj2.1-dt2.2-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.11-dt1.19-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.11-dt1.21-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.11-dt1.19-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.11-dt1.21-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.9-dt1.15-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.9-dt1.16-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.10-dt1.15-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.10-dt1.16-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.11-dt1.15-tests
    - python: '2.7'
      env: TOXENV=py27-dj1.11-dt1.16-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.9-dt1.15-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.9-dt1.16-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.10-dt1.15-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.10-dt1.16-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.11-dt1.15-tests
    - python: '3.6'
      env: TOXENV=py36-dj1.11-dt1.16-tests
    - python: '2.7'
      env: TOXENV=py27-flake
    - python: '3.6'
      env: TOXENV=py36-flake
    - python: '3.6'
      env: TOXENV=py36-isort

  allow_failures:
    - python: '3.8'
      env: TOXENV=py38-djmaster-dtmaster-tests
    - python: '3.8'
      env: TOXENV=py38-dj3.0-dtmaster-tests
    - python: '3.8'
      env: TOXENV=py38-dj3.1-dtmaster-tests

install:
  - pip install tox>=3.23.0
script:
  - tox
